config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'users/index'
  get 'users/show'

  get 'company/show' => 'company#show'
  get 'about' => 'about#company_overview'

  get 'inquiry/index' => 'inquiry#index'
  get 'inquiry/list' => 'inquiry#list'
  get 'inquiry/show' => 'inquiry#show'
  get 'inquiry/receive_email' => 'inquiry#receive_email'
  post 'inquiry/index' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :blogs do
    resources :comments
  end
  resources :comments
  resources :relationships, only: [:create, :destroy]
  get 'relationships/create'
  get 'relationships/destroy'

  resources :questions do
    resources :answers
  end
  resources :answers

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    member do
      get :following, :followers
    end
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
    resources :notifications, only: [:index]
    get 'notifications/list' => 'notifications#list'
    get 'notifications/more' => 'notifications#more'
  end

  namespace :taskline do
    resources :tasks do
      resources :comment
      post 'goodjob'
      post 'ungoodjob'
    end
  end

  scope module: :project do
    resources :projects do
      resources :tasks, except: :destroy
      delete 'tasks/:id' => 'tasks#sub_destroy'
      resources :members
    end
    resources :customers
  end

  namespace :taskline do
    resources :task_comments
  end

  resources :tasks

  resources :conversations do
    resources :messages
  end

  root 'top#index'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :sender, class_name: 'Conversation', foreign_key: :sender_id
  belongs_to :recipient, class_name: 'Conversation', foreign_key: :recipient_id
  belongs_to :comment, class_name: 'Comment', foreign_key: :comment_id
  belongs_to :submit_request

  scope :read, -> { where(read: true) }
  scope :unread, -> { where(read: false) }
  scope :unread_count, -> (user_id) { where(recipient_id: user_id).unread.count }

  def sender_user
    User.find(self.sender_id)
  end

  def receive_user
    User.find(self.recipient_id)
  end

  def posted_time
    self.created_at.strftime("%Y-%m-%d %H:%M:%S")
  end

  def display_read_status
    if self.read
      return '既読'
    else
      return '未読'
    end
  end

  def self.sending_pusher(channel_user_id)
    Pusher.trigger("notifications#{channel_user_id}", 'message', {
        unread_count: Notification.unread_count(channel_user_id)
    })
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications_all_count = Notification.where(recipient_id: current_user.id).reverse_order.includes({ comment: [:blog] }).count
    @notifications = Notification.where(recipient_id: current_user.id).reverse_order.includes({ comment: [:blog] }).limit(5)
    @notifications.update_all(read: true)
  end

  def more
    count = params[:count]
    limit_num = count.to_i * 5 + 5

    @notifications_all_count = Notification.where(recipient_id: current_user.id).reverse_order.includes({ comment: [:blog] }).count
    @notifications = Notification.where(recipient_id: current_user.id).reverse_order.includes({ comment: [:blog] }).limit(limit_num)
    @notifications.update_all(read: true)

    respond_to do |format|
      format.js
    end
  end

  def list
    @notifications_replace = Notification.where(recipient_id: current_user.id).reverse_order.includes({ comment: [:blog] }).unread
    @notifications_count_replace =  @notifications_replace.count

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_index.html.erb
<ul class="notifications-list">
  <% if notifications.present? %>
    <% notifications.each do |noti| %>
      <% # list用 %>
      <% unless noti.read %>
        <li class="notification-item">
          <span class="label label-pill label-warning">未読</span>
          <small class="dropdown">
            <% if noti.comment_id.present? %>
              ブログ「<%= link_to noti.comment.blog.title, blog_path(noti.comment.blog) %>」に<%= link_to noti.sender_user.name, user_path(noti.sender_user) %>さんがコメントしました。
            <% else %>
              <%= link_to noti.submit_request.user.name, user_path(noti.submit_request.user_id) %>さんが、タスク「<%= link_to noti.submit_request.task.title, submit_request_path(noti.submit_request) %>」を依頼しました。
            <% end %>
          </small>
          <div class="palette-paragraph h-tar">
            <small class="dropdown">
              <i class="fa fa-clock-o"></i>
              <%= noti.posted_time %>
            </small>
          </div>
        </li>
      <% # index用 %>
      <% else %>
        <li class="notification-item">
          <span class="label label-pill label-default h-mr5 h-vam">既読</span>
          <small class="dropdown">
            <% if noti.comment_id.present? %>
                ブログ「<%= link_to noti.comment.blog.title, blog_path(noti.comment.blog) %>」に<%= link_to noti.sender_user.name, user_path(noti.sender_user) %>さんがコメントしました。
            <% else %>
                タスク「<%= link_to noti.submit_request.task.title, submit_request_path(noti.submit_request) %>」を<%= link_to noti.submit_request.user.name, user_path(noti.submit_request.user_id) %>さんが依頼しました。
            <% end %>
          </small>
          <div class="palette-paragraph h-tar">
            <small class="dropdown">
              <i class="fa fa-clock-o"></i>
              <%= noti.posted_time %>
            </small>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/notifications/_list.html.erb
<div>
  <% if notice_count > 0 %>
      <% link_str = '全て見る' %>
      <%= render 'notifications/index', notifications: notices %>
  <% else %>
      <% link_str = '過去のお知らせを見る' %>
      <div class="text-danger h-tac">新着情報はありません</div>
  <% end %>
</div>
<li>
  <hr class="h-mt5 h-mb5">
  <%= link_to link_str, user_notifications_path(current_user) %>
</li>

app/views/notifications/index.html.erb
<script type="text/javascript" charset="utf-8">
  var replace_dom = "<div class='text-danger h-tac'>新着情報はありません</div>";

  $('title').html('Dive into Code');
  $('#js_notice_count').removeClass('text-primary');
  $('#js_unread_count').html('0');
  $('#js_notifications_list').html(replace_dom);

  var count = 0;
  function counter() {
    return ++count;
  }

  function more() {
    $.ajax({
      url: "<%= user_notifications_more_path(current_user.id) %>",
      type: 'GET',
      data: 'count=' + counter()
    });

    return false;
  }
</script>

<div class="notifications-wrap">
  <h2 class="page-header">お知らせ一覧</h2>

  <div class="h-mb15 h-ml10">
    全<%= @notifications_all_count %>件
  </div>

  <div id="js_notifications_index" class="notifications-content">
    <% if @notifications.count > 0 %>
      <%= render partial: 'notifications/index', locals: { notifications: @notifications } %>
    <% else %>
      <div class="text-danger">
        お知らせが見つかりませんでした
      </div>
    <% end %>
  </div>

  <% if @notifications.count > 4 %>
    <div class="h-tac">
      <button id="js_more_btn" class="btn btn-primary" onclick="more()">
        もっと見る
      </button>
    </div>
  <% end %>
</div>

app/views/notifications/list.js.erb
var render_target = $('#js_notifications_list'),
    render_str = "<%= escape_javascript(render partial: 'notifications/list', locals: { notices: @notifications_replace, notice_count: @notifications_count_replace }) %>",
    count_target = $('#js_notice_count');

render_target.html(render_str);
count_target.addClass('text-primary');

app/views/notifications/more.js.erb
var render_target = $('#js_notifications_index'),
    render_str = "<%= escape_javascript(render partial: 'notifications/index', locals: { notifications: @notifications }) %>";

var dfd = new $.Deferred();

render_target.html(render_str).hide()
             .slideDown('normal', function () {
               dfd.resolve();
             });

dfd.promise().then(function () {
  $('body').animate({
    scrollTop: $(document).height()
  }, 300);
});

<% if @notifications.count == @notifications_all_count %>
  var more_btn = $('#js_more_btn');
  more_btn.hide();
<% end %>