config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'users/index'
  get 'users/show'

  get 'company/show' => 'company#show'
  get 'about' => 'about#company_overview'

  get 'inquiry/index' => 'inquiry#index'
  get 'inquiry/list' => 'inquiry#list'
  get 'inquiry/show' => 'inquiry#show'
  get 'inquiry/receive_email' => 'inquiry#receive_email'
  post 'inquiry/index' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :blogs do
    resources :comments
  end
  resources :comments
  resources :relationships, only: [:create, :destroy]
  get 'relationships/create'
  get 'relationships/destroy'

  resources :questions do
    resources :answers
  end
  resources :answers

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    member do
      get :following, :followers
    end
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
    resources :notifications, only: [:index]
    get 'notifications/list' => 'notifications#list'
    get 'notifications/more' => 'notifications#more'
  end

  namespace :taskline do
    resources :tasks do
      resources :comment
      post 'goodjob'
      post 'ungoodjob'
    end
  end

  scope module: :project do
    resources :projects do
      resources :tasks, except: :destroy
      delete 'tasks/:id' => 'tasks#sub_destroy'
      resources :members
    end
    resources :customers
  end

  namespace :taskline do
    resources :task_comments
  end

  resources :tasks

  resources :conversations do
    resources :messages
  end

  root 'top#index'
end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :charger, class_name: 'User', foreign_key: 'charge_id'
  has_many :notifications, dependent: :destroy

  # 依頼作成時にお知らせも作成する
  accepts_nested_attributes_for :notifications

  delegate :name, to: :user, prefix: true
end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy]
  before_action :sub_set_submit_request, only: [:approve, :unapprove, :reject]

  def index
    @submit_requests = SubmitRequest.where(user_id: current_user.id).order(updated_at: :desc)
  end

  def new
    ids = current_user.friend.map { |user| user.id }
    @users = User.where(id: ids)
    @tasks = Task.where.not(id: SubmitRequest.select(:task_id))
                 .where(user_id: current_user.id, done: false)
    @submit_request = current_user.submit_requests.build(status: 1)
    @user = @submit_request.user
  end

  def create
    @submit_request = SubmitRequest.new(submit_request_params)
    @notification = @submit_request.notifications.build(recipient_id: @submit_request.charge_id, sender_id: current_user.id, read: false)

    respond_to do |format|
      if @submit_request.save
        @submit_request.task.update(status: 0)
        format.html { redirect_to @submit_request, notice: '依頼を作成しました' }
      else
        format.html { rendeer :new }
      end
    end
  end

  def show
  end

  def edit
    ids = current_user.friend.map { |user| user.id }
    @users = User.where(id: ids)
    @tasks = Task.where(user_id: current_user.id, done: false)
                 .where.not(id: SubmitRequest.select(:task_id))
  end

  def update
    respond_to do |format|
      if @submit_request.update(submit_request_params)
        @submit_request.task.update(charge_id: submit_request_params[:charge_id])
        format.html { redirect_to @submit_request, notice: '依頼を更新しました' }
      else
        format.html { rendeer :edit }
      end
    end
  end

  def destroy
  end

  def approve
    @submit_request.update(status: 2)
    @submit_request.task.update(charge_id: current_user.id)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).reverse_order

    respond_to do |format|
      format.js
    end
  end

  def unapprove
    @submit_request.update(status: 9, charge_id: @submit_request.user_id)
    @submit_request.task.update(charge_id: @submit_request.user_id)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).reverse_order

    respond_to do |format|
      format.js
    end
  end

  def reject
    @submit_request.update(status: 8)
    @submit_request.task.update(charge_id: current_user.id)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).reverse_order

    respond_to do |format|
      format.js
    end
  end

  def inbox
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).reverse_order
  end

  private

    def submit_request_params
      params.require(:submit_request).permit(:task_id, :user_id, :charge_id, :status, :message)
    end

    def set_submit_request
      @submit_request = SubmitRequest.find(params[:id])
    end

    def sub_set_submit_request
      @submit_request = SubmitRequest.find(params[:submit_request_id])
    end
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
end

app/views/submit_requests/_form.html.erb
<%= form_for([@user, @submit_request]) do |f| %>
  <div class="form-group">
    <%= f.label :task_id, 'タスク題名' %><br />
    <% if params['action'] == 'edit' %>
      <%= @submit_request.task.title %>
    <% else %>
      <%= f.collection_select :task_id, @tasks, :id, :title %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :task_id, '担当者' %><br />
    <%= f.collection_select :charge_id, @users, :id, :name %>
  </div>

  <div class="form-group">
    <%= f.text_area :message, placeholder: '依頼メッセージを入力してください', size: '50*100', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :status %>
    <%
      if params['action'] == 'edit'
        submit_str = '依頼を編集する'
      else
        submit_str = '依頼する'
      end
    %>
    <%= f.submit submit_str, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/submit_requests/_submit_requests_list.html.erb
<% if submit_requests.present? %>
  <div>
    <%= submit_requests.count %>件
  </div>
  <div>
    <table class="table table-striped">
      <thead>
        <th>状態</th>
        <th>タスク題名</th>
        <th>依頼者</th>
        <th>担当者</th>
        <th>依頼日</th>
        <th>タスクの状態</th>
        <th></th>
      </thead>
      <tbody>
        <% submit_requests.each do |sr| %>
          <tr>
            <% if sr.status == 1 %>
              <td>未承認</td>
            <% elsif sr.status == 2 %>
              <td>承認済み</td>
            <% elsif sr.status == 8 %>
              <td>取消済</td>
            <% elsif sr.status == 9 %>
              <td>却下</td>
            <% end %>

            <td>
              <%= link_to sr.task.title, user_task_path(sr.task.user_id, sr.task) %>
            </td>

            <% if sr.user_id == current_user.id %>
              <td>(自分)</td>
            <% else %>
              <td><%= sr.user.name %></td>
            <% end %>

            <% if sr.charge_id == current_user.id %>
                <td>(自分)</td>
            <% else %>
                <td><%= sr.charger.name %></td>
            <% end %>

            <td><%= sr.created_at.strftime("%Y/%m/%d") %></td>

            <% if sr.task.done == true %>
              <td>完了</td>
            <% else %>
              <td>未完了</td>
            <% end %>
            <td>
              <%= link_to '詳細', submit_request_path(sr) %>
              <% unless sr.user_id == current_user.id %>
                / <%= link_to '承認', submit_request_approve_path(sr), remote: true %>
                / <%= link_to '却下', submit_request_unapprove_path(sr), remote: true %>
              <% else %>
                  <% unless sr.status == 1 %>
                    <% unless sr.status == 2 %>
                      / <%= link_to '編集', edit_submit_request_path(sr) %>
                    <% end %>

                    / <%= link_to '取消', submit_request_reject_path(sr), data: sr.id, remote: true %>
                  <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/submit_requests/approve.js.erb
var renderStr = "<%= escape_javascript(render partial: 'submit_requests_list', locals: { submit_requests: @submit_requests }) %>";
var $renderTarget = $("#js_submit_requests_<%= current_user.id %>");
var $alert_target = $('#js_alert_target');
var dfd = new $.Deferred();
var dfd2 = new $.Deferred();

render($renderTarget, renderStr);

function render(target, dom) {
  $renderTarget.html(dom);
  dfd.resolve();
}

dfd.promise().then(function(){
  $alert_target.html('<div class="alert alert-info">依頼を承認しました</div>')
               .fadeIn('normal', dfd2.resolve);
  $('tbody').addClass('flash animated');
});

dfd2.promise().then(function () {
  setTimeout(function () {
    $alert_target.fadeOut('normal', function () {
      $alert_target.html('');
      $('tbody').removeClass('flash animated');
    });
  }, 800);
});

app/views/submit_requests/create.html.erb
<h1>SubmitRequests#create</h1>
<p>Find me in app/views/submit_requests/create.html.erb</p>

app/views/submit_requests/destroy.html.erb
<h1>SubmitRequests#destroy</h1>
<p>Find me in app/views/submit_requests/destroy.html.erb</p>

app/views/submit_requests/edit.html.erb
<div class="submit-requests-wrap">
  <h2 class="page-header">依頼編集</h2>

  <%= render 'form' %>

  <div class="h-mb15">
    <%= link_to '依頼詳細', submit_request_path(@submit_request), class: 'btn btn-default' %>
  </div>
  <div class="h-mb15">
    <%= link_to '依頼一覧', user_submit_requests_path(@submit_request), class: 'btn btn-default' %>
  </div>
</div>

app/views/submit_requests/inbox.html.erb
<div id="js_alert_target"></div>

<div class="submit-requests-wrap">
  <h2 class="page-header">受けている依頼一覧</h2>

  <div class="h-mb15">
    <%= link_to '依頼一覧', user_submit_requests_path(current_user.id), class: 'btn btn-default' %>
  </div>

  <div id="js_submit_requests_<%= current_user.id %>">
    <%= render partial: 'submit_requests_list', locals: { submit_requests: @submit_requests } %>
  </div>
</div>

app/views/submit_requests/index.html.erb
<div id="js_alert_target"></div>

<div class="submit-requests-wrap">
  <h2 class="page-header">依頼一覧</h2>

  <div class="h-mb15">
    <%= link_to '新規依頼', new_user_submit_request_path, class: 'btn btn-default' %>
  </div>
  <div class="h-mb15">
    <%= link_to '受けている依頼一覧', inbox_user_submit_requests_path, class: 'btn btn-default' %>
  </div>

  <div id="js_submit_requests_<%= current_user.id %>">
    <%= render partial: 'submit_requests_list', locals: { submit_requests: @submit_requests } %>
  </div>
</div>

app/views/submit_requests/new.html.erb
<div class="submit-requests-wrap">
  <h2 class="page-header">新規依頼</h2>

  <div>
    <h4>依頼するタスク</h4>
    <div class="h-mb15">
      <% if @tasks.present? %>
        <%= render 'form' %>
      <% else %>
          <div class="text-danger">
            依頼できるタスクがありません
          </div>
      <% end %>
    </div>
  </div>

  <%= link_to '依頼一覧に戻る', user_submit_requests_path(@submit_request.user_id), class: 'btn btn-default' %>
</div>

app/views/submit_requests/reject.js.erb
var renderStr = "<%= escape_javascript(render partial: 'submit_requests_list', locals: { submit_requests: @submit_requests }) %>";
var $renderTarget = $("#js_submit_requests_<%= current_user.id %>");
var $alert_target = $('#js_alert_target');
var dfd = new $.Deferred();
var dfd2 = new $.Deferred();

render($renderTarget, renderStr);

function render(target, dom) {
  $renderTarget.html(dom);
  dfd.resolve();
}

dfd.promise().then(function(){
  $alert_target.html('<div class="alert alert-info">依頼を取消しました</div>')
      .fadeIn('normal', dfd2.resolve);
  $('tbody').addClass('flash animated');
});

dfd2.promise().then(function () {
  setTimeout(function () {
    $alert_target.fadeOut('normal', function () {
      $alert_target.html('');
      $('tbody').removeClass('flash animated');
    });
  }, 800);
});

app/views/submit_requests/show.html.erb
<div class="submit-requests-wrap">
  <h2 class="page-header">依頼詳細</h2>

  <div class="submit-requests-content">
    <div>
      <b>依頼作成者:</b>
      <%= @submit_request.user.name if @submit_request.user.present? %>
    </div>

    <div>
      <b>タスク題名:</b>
      <%= @submit_request.task.title %>
    </div>

    <div>
      <b>担当者:</b>
      <%= @submit_request.charger.name if @submit_request.user.present? %>
    </div>

    <div>
      <b>状態:</b>
      <%= case @submit_request.status
          when 0 then "未依頼"
          when 1 then "依頼中"
          when 2 then "承認済み"
          when 8 then "取消済み"
          when 9 then "却下済み"
          end
      %>
    </div>

    <div class="simple-text-l h-mb15">
      <b>メッセージ:</b>
      <div class="">
        <%= simple_format(h(@submit_request.message)) %>
      </div>
    </div>
  </div>

  <div class="h-mb15">
    <%= link_to '依頼編集', edit_submit_request_path(@submit_request), class: 'btn btn-default' %>
  </div>
  <%= link_to '依頼一覧', user_submit_requests_path(@submit_request.user_id), class: 'btn btn-default' %>
</div>

app/views/submit_requests/unapprove.js.erb
var renderStr = "<%= escape_javascript(render partial: 'submit_requests_list', locals: { submit_requests: @submit_requests }) %>";
var $renderTarget = $("#js_submit_requests_<%= current_user.id %>");
var $alert_target = $('#js_alert_target');
var dfd = new $.Deferred();
var dfd2 = new $.Deferred();

render($renderTarget, renderStr);

function render(target, dom) {
  $renderTarget.html(dom);
  dfd.resolve();
}

dfd.promise().then(function(){
  $alert_target.html('<div class="alert alert-info">依頼を却下しました</div>')
      .fadeIn('normal', dfd2.resolve);
  $('tbody').addClass('flash animated');
});

dfd2.promise().then(function () {
  setTimeout(function () {
    $alert_target.fadeOut('normal', function () {
      $alert_target.html('');
      $('tbody').removeClass('flash animated');
    });
  }, 800);
});

app/views/submit_requests/update.html.erb
<h1>SubmitRequests#update</h1>
<p>Find me in app/views/submit_requests/update.html.erb</p>