config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'users/index'
  get 'users/show'

  get 'company/show' => 'company#show'
  get 'about' => 'about#company_overview'

  get 'inquiry/index' => 'inquiry#index'
  get 'inquiry/list' => 'inquiry#list'
  get 'inquiry/show' => 'inquiry#show'
  get 'inquiry/receive_email' => 'inquiry#receive_email'
  post 'inquiry/index' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :blogs do
    resources :comments
  end
  resources :comments
  resources :relationships, only: [:create, :destroy]
  get 'relationships/create'
  get 'relationships/destroy'

  resources :questions do
    resources :answers
  end
  resources :answers

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    member do
      get :following, :followers
    end
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
    resources :notifications, only: [:index]
    get 'notifications/list' => 'notifications#list'
    get 'notifications/more' => 'notifications#more'
  end

  namespace :taskline do
    resources :tasks do
      resources :comment
      post 'goodjob'
      post 'ungoodjob'
    end
  end

  scope module: :project do
    resources :projects do
      resources :tasks, except: :destroy
      delete 'tasks/:id' => 'tasks#sub_destroy'
      resources :members
    end
    resources :customers
  end

  namespace :taskline do
    resources :task_comments
  end

  resources :tasks

  resources :conversations do
    resources :messages
  end

  root 'top#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    @question = @answer.question
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @question = @answer.question

    # 投稿を操作するユーザがログイン中のユーザか判定(alertはajaxで制御)
    if @answer.user_id != current_user.id
      return render 'answers/show.js.erb', params: 'error'
    end

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
        format.js { render :show, notice: '回答を投稿しました' }

        # 回答が投稿されたら、質問者にメールを送る
        if @question.user.provider.empty?
          logger.debug "メール送るよ #{@question.user.provider}"
          @inquiry = Inquiry.new(name: @answer.user.name, email: @question.user.email, message: @answer.content)
          InquiryMailer.send_notice_answer_email(@inquiry).deliver
        end
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    tmp = params.require(:answer).permit(:user_id)
    @user = User.find(tmp["user_id"])

    # 投稿を操作するユーザがログイン中のユーザか判定
    if @answer.user_id != current_user.id || @user.id != current_user.id
      redirect_to questions_path, alert: '不正な操作が行われました'
      return
    end

    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer.question, notice: '回答を編集しました' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @question = @answer.question

    # 投稿を操作するユーザがログイン中のユーザか判定
    if @answer.user_id != current_user.id
      return render 'answers/show.js.erb', params: 'error'
    end

    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render :show, notice: '回答を削除しました' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%
  if local === 'show'
    submit_str = '回答する'
    ajax_flg = true
  else
    submit_str = '回答を編集する'
    ajax_flg = false
  end
%>

<%= form_for(answer, remote: ajax_flg) do |f| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fm-answer h-dt">
    <div class="form-group h-dtc h-pr10 h-w100p">
      <%= f.hidden_field :question_id %>
      <%= f.hidden_field :user_id %>
      <%= f.text_area :content, class: 'form-control', placeholder: '回答を入力してください', rows: 1 %>
    </div>

    <div class="form-group h-dtc h-vat">
      <%= f.submit submit_str, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/answers/_show.html.erb
<% answers.each do |answer| %>
  <% unless answer.id.nil? %>
    <div class="answer-item h-dt h-w100p">
      <div class="profile-img h-dtc h-vat h-pr10">
        <%= link_to user_path(answer.user.id) do %>
            <%= profile_img(answer.user, { class: 'media-object img-thumbnail' }) %>
        <% end %>
      </div>
      <div class="h-dtc h-vat">
        <div class="content-text well well-sm h-mb5">
          <%= simple_format(h(answer.content)) %>
        </div>
        <div>
          <span class="h-fwb">回答者:</span> <%= link_to answer.user.name, user_path(answer.user.id) %><br>
          <span class="h-fwb">投稿日:</span> <%= answer.created_at.to_s(:db) %> /
          <span class="h-fwb">更新日:</span> <%= answer.updated_at.to_s(:db) %>
        </div>
        <div class="h-dt h-w100p h-tar">
          <% if answer.user.id === current_user.id %>
            <%= link_to '編集', edit_question_answer_path(@question, answer.id), class: 'h-pr5' %>
            <%= link_to '削除', question_answer_path(@question, answer.id), method: :delete, remote: true, data: {
                confirm: '本当に削除しますか？',
                commit: '削除する',
                cancel: 'やめる'
            },  title: '回答の削除確認' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/answers/edit.html.erb
<div class="questions-wrap">
  <h2 class="page-header">回答編集</h2>
  <div class="answers-edit h-mb20">
    <%= render partial: 'answers/form', locals: { answer: @answer, local: 'edit' } %>
  </div>

  <%= link_to '質問詳細に戻る', @question, class: 'btn btn-default' %>
</div>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question %></td>
        <td><%= answer.user %></td>
        <td><%= answer.content %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/answers/show.js.erb
var render_str = '<%= escape_javascript(render partial: "answers/show", locals: { answers: @question.answers }) %>'

<% if @answer.user_id != current_user.id %>
  var alert_elm = '<div class="js_alert alert alert-danger animated fadeIn" role="alert">' +
          '不正な操作が行われました' +
          '</div>',
      alert_target = $('#js_alert_target');

  $('html, body').animate({ scrollTop: 0 }, 'fast');
  alert_target.html(alert_elm);
  alert_target.fadeIn();

  util = new Util;
  util.elmVanising(alert_target, 1500);
<% else %>
  replace(render_str);
<% end %>

function replace(str) {
  $('#js_answers_area').html(str);
  $('textarea').val('');
}