config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'users/index'
  get 'users/show'

  get 'company/show' => 'company#show'
  get 'about' => 'about#company_overview'

  get 'inquiry/index' => 'inquiry#index'
  get 'inquiry/list' => 'inquiry#list'
  get 'inquiry/show' => 'inquiry#show'
  get 'inquiry/receive_email' => 'inquiry#receive_email'
  post 'inquiry/index' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :blogs do
    resources :comments
  end
  resources :comments
  resources :relationships, only: [:create, :destroy]
  get 'relationships/create'
  get 'relationships/destroy'

  resources :questions do
    resources :answers
  end
  resources :answers

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    member do
      get :following, :followers
    end
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
    resources :notifications, only: [:index]
    get 'notifications/list' => 'notifications#list'
    get 'notifications/more' => 'notifications#more'
  end

  namespace :taskline do
    resources :tasks do
      resources :comment
      post 'goodjob'
      post 'ungoodjob'
    end
  end

  scope module: :project do
    resources :projects do
      resources :tasks, except: :destroy
      delete 'tasks/:id' => 'tasks#sub_destroy'
      resources :members
    end
    resources :customers
  end

  namespace :taskline do
    resources :task_comments
  end

  resources :tasks

  resources :conversations do
    resources :messages
  end

  root 'top#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :customer
  has_many :members, dependent: :destroy
  has_many :tasks, dependent: :destroy

  # projectのメンバーか判定
  def members?(user)
    members = Member.where(project_id: self.id).where(user_id: user.id)
    ! members[0].nil?
  end

  # projectの作成者か判定
  def manager?(user)
    project = Project.find(self.id)
    project.user == user
  end

  # projectのメンバーか判定
  def project_members?(user)
    project_members = self.members.find_by(user_id: user.id)
    ! project_members.nil?
  end
end

app/controllers/project/customers_controller.rb
class Project::CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:edit, :update]

  def index
    @customers = Customer.all.reverse_order
    @customer  = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: '顧客を登録しました' }
        format.json { render :index, status: :created, location: @customer }
      else
        format.html { render :index }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: '顧客情報を編集しました' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # プロジェクトから参照されるため、削除機能はつけない
  def destroy
  end

  private
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name)
  end
end

app/controllers/project/members_controller.rb
class Project::MembersController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @users = User.all
  end

  def create
    @project = Project.find(params[:project_id])
    @member = @project.members.build(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to project_members_path(@project), notice: 'プロジェクトメンバーに追加しました' }
      end
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @member = Member.find(params[:id])
    @member.destroy
    respond_to do |format|
      format.html { redirect_to project_members_path(@project), notice: 'プロジェクトメンバーから外しました' }
    end
  end

  private

    def member_params
      params.require(:member).permit(:user_id, :project_id)
    end
end

app/controllers/project/projects_controller.rb
class Project::ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @members = @project.members
    @tasks   = @project.tasks
  end

  def new
    @project = Project.new(user_id: current_user.id)
    @customers = Customer.all
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'プロジェクトを作成しました' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @customers = Customer.all
  end

  def update
    # 投稿を操作するユーザがログイン中のユーザか判定
    tmp = params.require(:project).permit(:user_id)
    @user = User.find(tmp["user_id"])
    if @project.user_id != current_user.id || @user.id != current_user.id
      redirect_to projects_path, alert: '不正な操作が行われました'
      return
    end

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'プロジェクトを編集しました' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # 投稿を操作するユーザがログイン中のユーザか判定
    if @project.user_id != current_user.id
      redirect_to projects_path, alert: '不正な操作が行われました'
      return
    end

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'プロジェクトを削除しました' }
      format.json { head :no_content }
    end
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :content, :user_id, :customer_id)
  end
end

app/controllers/project/tasks_controller.rb
class Project::TasksController < TasksController
  # ベースはTasksControllerから継承して、リダイレクト処理のみこちらで制御
  skip_before_filter :correct_user # correct_userフィルターを除外
  before_action :set_project

  def show
  end

  def new
    @project_task = Task.new(user_id: current_user.id, charge_id: current_user.id, project_id: @project.id)
  end

  def create
    @project_task = @project.tasks.build(project_task_params)

    # 投稿を操作するユーザがログイン中のユーザか判定
    unless @project_task.user_id == current_user.id
      redirect_to @project, alert: '不正な操作が行われました'
      return
    end

    respond_to do |format|
      if @project_task.save
        format.html { redirect_to project_task_path(@project, @project_task.id), notice: 'プロジェクトのタスクを作成しました' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @project_task = @task
  end

  def update
    @project_task = @task

    # 投稿を操作するユーザがログイン中のユーザか判定
    unless @project_task.user_id == current_user.id
      redirect_to @project, alert: '不正な操作が行われました'
      return
    end

    respond_to do |format|
      if @project_task.update(project_task_params)
        format.html { redirect_to project_task_path(@project, @project_task), notice: 'タスクが更新されました' }
        format.json { render :show, status: :ok, location: @project_task }
      else
        format.html { render :edit }
        format.json { render json: @project_task.errors, status: :unprocessable_entity }
      end
    end
  end

  def sub_destroy
    @project_task = Task.find(params[:id])

    @project_task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'タスクを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def project_task_params
      params.require(:task).permit(:user_id, :title, :content, :deadline, :charge_id, :done, :status)
    end

    def project_params
      params.require(:project).permit(:name, :content, :user_id, :customer_id)
    end
end

app/helpers/project/customers_helper.rb
module Project::CustomersHelper
end

app/helpers/project/members_helper.rb
module Project::MembersHelper
end

app/helpers/project/projects_helper.rb
module Project::ProjectsHelper
end

app/helpers/project/tasks_helper.rb
module Project::TasksHelper
end

app/views/project/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, '題名' %><br>
      <%= f.text_field :name, class: 'form-control', placeholder: 'プロジェクト名を入力してください' %>
    </div>
    <div class="form-group">
      <%= f.label :content, '内容' %><br>
      <%= f.text_area :content, class: 'form-control', placeholder: '内容を入力してください' %>
    </div>
    <div class="form-group">
      <%= f.label :customer_id, '顧客' %><br>
      <%= f.select :customer_id, @customers.map{|t| [t.name, t.id]}, prompt: "選択してください", class: 'form-control' %>
    </div>

    <%
      if params['action'] == 'edit'
        submit_str = 'プロジェクト情報を変更する'
      else
        submit_str = 'プロジェクトを作成する'
      end
    %>
    <div class="form-group">
      <%= f.hidden_field :user_id %>
      <%= f.submit submit_str, class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/project/projects/edit.html.erb
<div class="projects-wrap">
  <h2 class="page-header">プロジェクト編集</h2>

  <div class="h-mb15">
    <%= render 'form' %>
  </div>

  <div class="h-mb15">
    <%= link_to 'プロジェクトを削除する', project_path(@project), method: :delete,
                data: { confirm: '本当に削除しますか？',
                        commit: '削除する',
                        cancel: 'やめる'
                }, title: 'プロジェクトの削除確認', class: 'btn btn-danger' %>
  </div>
  <%= link_to 'プロジェクト一覧に戻る', projects_path, class: 'btn btn-default' %>
</div>

app/views/project/projects/index.html.erb
<div class="projects-wrap">
  <h2 class="page-header">プロジェクト一覧</h2>

  <%= link_to 'プロジェクト作成', new_project_path, class: 'btn btn-default h-mb15' %>
  <%= link_to '顧客管理', customers_path, class: 'btn btn-default h-mb15' %>

  <div class="text-danger h-mb15">
    各プロジェクトの閲覧・操作は作成者およびメンバーのみ可能です
  </div>

  <table class="table table-striped">
    <thead>
    <tr>
      <th><b>プロジェクト名</b></th>
      <th><b>作成者</b></th>
      <th><b>顧客名</b></th>
      <th class="h-tar"><b>閲覧・操作</b></th>
    </tr>
    </thead>

    <tbody>
    <% unless @projects.empty? %>
      <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.user.name %></td>
            <%
              if project.customer_id.nil?
                customer_name = '顧客無し'
              else
                customer_name = project.customer.name
              end
            %>
            <td><%= customer_name %></td>
            <td class="h-tar">
              <% if project.members?(current_user) || project.manager?(current_user) %>
                <%= link_to '詳細', project_path(project) %>
                / <%= link_to '編集', edit_project_path(project) %>
                / <%= link_to_if project.manager?(current_user), '削除', project_path(project), method: :delete,
                              data: { confirm: '本当に削除しますか？',
                                      commit: '削除する',
                                      cancel: 'やめる'
                              }, title: 'プロジェクトの削除確認'  %>
              <% else %>
                閲覧権限がありません
              <% end %>
            </td>
          </tr>
      <% end %>
    <% else %>
        <tr>
          <td colspan="4">
            <div class="text-muted">プロジェクトが登録されていません</div>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/project/projects/new.html.erb
<div class="projects-wrap">
  <h2 class="page-header">プロジェクト作成</h2>

  <div class="h-mb15">
    <%= render 'form' %>
  </div>

  <%= link_to 'プロジェクト一覧に戻る', projects_path, class: 'btn btn-default' %>
</div>

app/views/project/projects/show.html.erb
<%
  if @project.customer_id.nil?
    customer_name = '顧客無し'
  else
    customer_name = @project.customer.name
  end
%>

<div class="projects-wrap">
  <h2 class="page-header"><%= @project.name %></h2>

  <div class="project-detail-content">
    <div class="h-dt h-w100p">
      <div class="h-dtc h-vam h-tal">
        <div class="h-mb10"><b>作成者:</b> <%= @project.user.name %></div>
        <div class="h-mb10"><b>顧客名:</b> <%= customer_name %></div>
      </div>
      <div class="h-dtc h-vam h-tar">
        <div class="h-mb15">
          <%= link_to 'プロジェクトを編集する', edit_project_path(@project), class: 'btn btn-default' %>
        </div>
        <div class="h-mb15">
          <%= link_to 'プロジェクト一覧に戻る', projects_path, class: 'btn btn-default' %>
        </div>
      </div>
    </div>

    <div class="h-mb10"><b>概要</b></div>
    <div class="well well-sm simple-text-l">
      <%= simple_format(h(@project.content)) %>
    </div>

    <h4 class="page-header">プロジェクトタスク</h4>
    <div class="h-pl10 h-pr10">
      <%= link_to 'タスク登録', new_project_task_path(@project), class: 'btn btn-default h-mb15' %>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>作成者</th>
          <th>題名</th>
          <th>内容</th>
          <th>期日</th>
          <th>担当者</th>
          <th>完了/未完了</th>
          <th>状態</th>
          <th class="h-tar"></th>
        </tr>
        </thead>
        <tbody>
        <% unless @tasks.empty? %>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= task.user.name %></td>
              <td><%= task.title %></td>
              <td><%= task.content %></td>
              <td><%= task.deadline.strftime("%Y-%m-%d %H:%M:%S") %></td>
              <td><%= task.charge.name %></td>
              <td><%= if task.done? then '完了' else '未完了' end %></td>
              <td><%= if task.status == 1 then '対応中' elsif task.status == 0 then '未着手' end %></td>
              <td class="h-tar">
                <%= link_to '詳細', project_task_path(@project, task) %> /
                <%= link_to '編集', edit_project_task_path(@project, task) %> /
                <%= link_to '削除', project_task_path(@project, task), method: :delete,
                              data: { confirm: '本当に削除しますか？',
                                      commit: '削除する',
                                      cancel: 'やめる'
                              }, title: 'タスクの削除確認'  %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="10"><div class="text-muted">タスクが登録されていません</div></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <h4 class="page-header">プロジェクトメンバー</h4>
    <div class="h-pl10 h-pr10">
      <div class="h-mb15">
       <%= link_to 'メンバー管理', project_members_path(@project), class: 'btn btn-default' %>
      </div>

      <% unless @members.empty? %>
        <% @members.each do |member| %>
          <%= link_to user_path(member.user), class: 'user-item' do %>
            <%= profile_img(member.user, { class: 'img-thumbnail' }) %>
            <div class="name h-tac">
              <b><%= member.user.name %></b>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="text-muted">
          メンバーが登録されていません
        </div>
      <% end %>
    </div>
  </div>
</div>